---
title: "reproducible document"
author: "Weixiao"
format: html
---

## Basic of R

```{r}
1 + 1
```

## Setup code chunk



```{r setup}
#| message :false
#| warning :false
library(tidyverse)
post_meal_data <- read_csv2(
  here::here("data/post-meal-insulin.csv")
)
```


##Showing the data

```{r}
post_meal_data

```


```{r}
glimpse(post_meal_data)
```


```{r}
ggplot(post_meal_data,aes(x = BMI))  +
  geom_histogram()

```


```{r}
#| fig-cap: "Distribution of BMI"
#| label: fig-bmi-histo
ggplot(post_meal_data,aes(x = BMI))  +
  geom_histogram()
```

@fig-bmi-histo


## Exercise: discrete plots

```{r}
#| fig-cap: "Distrubution of group"
#| label: fig-group-bar
ggplot(post_meal_data, aes(x = Group)) +
  geom_bar()

```

@fig-group-bar



## About me

-weixiao wang
-the institution of endocrine and metobolic 

I am a first-year PhD student at Kiel University, studying **Internal Medicine**. I am *passionate* about research and eager to learn new skills.

## Simple code
```{r}
3 * 3
```


## Testing for Git
Today is so cloudy.
